export const pictureProfil = [
  { name: "Aigle", uri: require("./assets/images/aigle.png") },
  { name: "Baleine", uri: require("./assets/images/baleine.png") },
  { name: "Calamar", uri: require("./assets/images/calamar.png") },
  { name: "Cameleon", uri: require("./assets/images/cameleon.png") },
  { name: "Cerf", uri: require("./assets/images/cerf.png") },
  { name: "Crocodile", uri: require("./assets/images/crocodile.png") },
  { name: "Dauphin", uri: require("./assets/images/dauphin.png") },
  { name: "Dragon", uri: require("./assets/images/dragon.png") },
  { name: "Dromadaire", uri: require("./assets/images/dromadaire.png") },
  { name: "Éléphant", uri: require("./assets/images/elephant.png") },
  { name: "Girafe", uri: require("./assets/images/girafe.png") },
  { name: "Hippocampe", uri: require("./assets/images/hippocampe.png") },
  { name: "Hippopotame", uri: require("./assets/images/hippopotame.png") },
  { name: "Hyène", uri: require("./assets/images/hyene.png") },
  { name: "Iguane", uri: require("./assets/images/iguane.png") },
  { name: "Kangourou", uri: require("./assets/images/kangourou.png") },
  { name: "Koala", uri: require("./assets/images/koala.png") },
  { name: "Léopard", uri: require("./assets/images/leopard.png") },
  { name: "Lion", uri: require("./assets/images/lion.png") },
  { name: "Loup", uri: require("./assets/images/loup.png") },
  { name: "Orque", uri: require("./assets/images/orque.png") },
  { name: "Ours", uri: require("./assets/images/ours.png") },
  { name: "Ours Polaire", uri: require("./assets/images/oursPolaire.png") },
  { name: "Panda", uri: require("./assets/images/panda.png") },
  { name: "Paresseux", uri: require("./assets/images/paresseux.png") },
  { name: "Poisson", uri: require("./assets/images/poisson.png") },
  { name: "Raccoon", uri: require("./assets/images/raccoon.png") },
  { name: "Raie", uri: require("./assets/images/raie.png") },
  { name: "Renard", uri: require("./assets/images/renard.png") },
  { name: "Rhinocéros", uri: require("./assets/images/rhinoceros.png") },
  { name: "Serpent", uri: require("./assets/images/serpent.png") },
  { name: "Singe", uri: require("./assets/images/singe.png") },
  { name: "Singe 2", uri: require("./assets/images/singe2.png") },
  { name: "Suricate", uri: require("./assets/images/suricate.png") },
  { name: "Taureau", uri: require("./assets/images/taureau.png") },
  { name: "Tigre", uri: require("./assets/images/tigre.png") },
  { name: "Tortue", uri: require("./assets/images/tortue.png") },
  { name: "Toucan", uri: require("./assets/images/toucan.png") },
  { name: "Zèbre", uri: require("./assets/images/zebre.png") },
];
